// Auto-generated from candidates.json
// Do not edit this file directly; edit candidates.json and regenerate.

const candidates = [
  {
    "candidate_id": "4e6a7727-ba03-46c4-86f7-63e2969c0e7f",
    "median_probability": "73.40098023414609",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      685017.0883,
      3402969.54293,
      686257.0883,
      3404209.54293
    ],
    "review_square_side_m": 1240.0,
    "display_pixel_size_m": 1.55,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/4e6a7727-ba03-46c4-86f7-63e2969c0e7f_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/4e6a7727-ba03-46c4-86f7-63e2969c0e7f_SAVI (Wet).png",
        "scale_path": "imgs/review_images/4e6a7727-ba03-46c4-86f7-63e2969c0e7f_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/4e6a7727-ba03-46c4-86f7-63e2969c0e7f_MSRM.png",
        "scale_path": "imgs/review_images/4e6a7727-ba03-46c4-86f7-63e2969c0e7f_MSRM_scale.png",
        "band": 42,
        "vmin": -0.12879694998264313,
        "vmax": 0.14512889087200165,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/4e6a7727-ba03-46c4-86f7-63e2969c0e7f_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/4e6a7727-ba03-46c4-86f7-63e2969c0e7f_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.155573844909668,
        "vmax": 1.3171799182891846,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.750781423031622, 70.93933121568595"
  },
  {
    "candidate_id": "f54a3652-6ad0-4597-9903-3dd5a29484bd",
    "median_probability": "85.1599931716919",
    "median_probability_category": "Very High",
    "image_size_px": 800,
    "review_square_bounds": [
      1138818.60436,
      3267152.65818,
      1140148.60436,
      3268482.65818
    ],
    "review_square_side_m": 1330.0,
    "display_pixel_size_m": 1.6625,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/f54a3652-6ad0-4597-9903-3dd5a29484bd_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/f54a3652-6ad0-4597-9903-3dd5a29484bd_SAVI (Wet).png",
        "scale_path": "imgs/review_images/f54a3652-6ad0-4597-9903-3dd5a29484bd_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/f54a3652-6ad0-4597-9903-3dd5a29484bd_MSRM.png",
        "scale_path": "imgs/review_images/f54a3652-6ad0-4597-9903-3dd5a29484bd_MSRM_scale.png",
        "band": 42,
        "vmin": -0.21933594346046448,
        "vmax": 0.18167906999588013,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/f54a3652-6ad0-4597-9903-3dd5a29484bd_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/f54a3652-6ad0-4597-9903-3dd5a29484bd_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.1558111906051636,
        "vmax": 1.3801909685134888,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.376938606884394, 75.58203176884993"
  },
  {
    "candidate_id": "62d9814d-f0d7-4013-82dc-fd8465a7331c",
    "median_probability": "92.340612411499",
    "median_probability_category": "Very High",
    "image_size_px": 800,
    "review_square_bounds": [
      796171.85371,
      3230083.11925,
      797671.85371,
      3231583.11925
    ],
    "review_square_side_m": 1500.0,
    "display_pixel_size_m": 1.875,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/62d9814d-f0d7-4013-82dc-fd8465a7331c_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/62d9814d-f0d7-4013-82dc-fd8465a7331c_SAVI (Wet).png",
        "scale_path": "imgs/review_images/62d9814d-f0d7-4013-82dc-fd8465a7331c_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/62d9814d-f0d7-4013-82dc-fd8465a7331c_MSRM.png",
        "scale_path": "imgs/review_images/62d9814d-f0d7-4013-82dc-fd8465a7331c_MSRM_scale.png",
        "band": 42,
        "vmin": -0.08616070449352264,
        "vmax": 0.08519023656845093,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/62d9814d-f0d7-4013-82dc-fd8465a7331c_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/62d9814d-f0d7-4013-82dc-fd8465a7331c_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.0315804481506348,
        "vmax": 1.1317377090454102,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.171397177170793, 72.05276842908012"
  },
  {
    "candidate_id": "b9ab1967-7e64-4b6a-822c-099e04846fc2",
    "median_probability": "71.312689781189",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      909203.97173,
      3395478.99381,
      910413.97173,
      3396688.99381
    ],
    "review_square_side_m": 1210.0,
    "display_pixel_size_m": 1.5125,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/b9ab1967-7e64-4b6a-822c-099e04846fc2_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/b9ab1967-7e64-4b6a-822c-099e04846fc2_SAVI (Wet).png",
        "scale_path": "imgs/review_images/b9ab1967-7e64-4b6a-822c-099e04846fc2_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/b9ab1967-7e64-4b6a-822c-099e04846fc2_MSRM.png",
        "scale_path": "imgs/review_images/b9ab1967-7e64-4b6a-822c-099e04846fc2_MSRM_scale.png",
        "band": 42,
        "vmin": -0.14972656965255737,
        "vmax": 0.20286011695861816,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/b9ab1967-7e64-4b6a-822c-099e04846fc2_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/b9ab1967-7e64-4b6a-822c-099e04846fc2_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.136619210243225,
        "vmax": 1.3247474431991577,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.627200297323597, 73.27425361072709"
  },
  {
    "candidate_id": "059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0",
    "median_probability": "83.3362877368927",
    "median_probability_category": "Very High",
    "image_size_px": 800,
    "review_square_bounds": [
      906053.97173,
      3388913.99381,
      907443.97173,
      3390303.99381
    ],
    "review_square_side_m": 1390.0,
    "display_pixel_size_m": 1.7375,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0_SAVI (Wet).png",
        "scale_path": "imgs/review_images/059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0_MSRM.png",
        "scale_path": "imgs/review_images/059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0_MSRM_scale.png",
        "band": 42,
        "vmin": -0.16136257350444794,
        "vmax": 0.15622998774051666,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/059bffb5-bf8b-4051-8ac8-35e7c3bf8dc0_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.1052809953689575,
        "vmax": 1.339483380317688,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.569976442182785, 73.2398694546968"
  },
  {
    "candidate_id": "26ce7b1c-c6bc-4c45-b916-908e747b7401",
    "median_probability": "70.8366513252258",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      771630.65837,
      3227659.44771,
      772870.65837,
      3228899.44771
    ],
    "review_square_side_m": 1240.0,
    "display_pixel_size_m": 1.55,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/26ce7b1c-c6bc-4c45-b916-908e747b7401_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/26ce7b1c-c6bc-4c45-b916-908e747b7401_SAVI (Wet).png",
        "scale_path": "imgs/review_images/26ce7b1c-c6bc-4c45-b916-908e747b7401_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/26ce7b1c-c6bc-4c45-b916-908e747b7401_MSRM.png",
        "scale_path": "imgs/review_images/26ce7b1c-c6bc-4c45-b916-908e747b7401_MSRM_scale.png",
        "band": 42,
        "vmin": -0.1755516678094864,
        "vmax": 0.18014661967754364,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/26ce7b1c-c6bc-4c45-b916-908e747b7401_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/26ce7b1c-c6bc-4c45-b916-908e747b7401_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.0539535284042358,
        "vmax": 1.45577871799469,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.15391708524847, 71.79875131666252"
  },
  {
    "candidate_id": "0843bc84-b1a8-43ca-ad50-fcb40ad047f1",
    "median_probability": "68.6163306236267",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      786572.0162607699,
      3215594.3449159474,
      787712.0162607699,
      3216734.3449159474
    ],
    "review_square_side_m": 1140.0,
    "display_pixel_size_m": 1.425,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/0843bc84-b1a8-43ca-ad50-fcb40ad047f1_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/0843bc84-b1a8-43ca-ad50-fcb40ad047f1_SAVI (Wet).png",
        "scale_path": "imgs/review_images/0843bc84-b1a8-43ca-ad50-fcb40ad047f1_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/0843bc84-b1a8-43ca-ad50-fcb40ad047f1_MSRM.png",
        "scale_path": "imgs/review_images/0843bc84-b1a8-43ca-ad50-fcb40ad047f1_MSRM_scale.png",
        "band": 42,
        "vmin": -0.2195195108652115,
        "vmax": 0.22097529470920563,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/0843bc84-b1a8-43ca-ad50-fcb40ad047f1_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/0843bc84-b1a8-43ca-ad50-fcb40ad047f1_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.068679928779602,
        "vmax": 1.1238287687301636,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.041429383044868, 71.94855566131544"
  },
  {
    "candidate_id": "ef439ec3-a802-4687-a2b4-25de4e871753",
    "median_probability": "68.3444380760193",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      765591.0301295605,
      3274925.3359528435,
      766691.0301295605,
      3276025.3359528435
    ],
    "review_square_side_m": 1100.0,
    "display_pixel_size_m": 1.375,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/ef439ec3-a802-4687-a2b4-25de4e871753_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/ef439ec3-a802-4687-a2b4-25de4e871753_SAVI (Wet).png",
        "scale_path": "imgs/review_images/ef439ec3-a802-4687-a2b4-25de4e871753_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/ef439ec3-a802-4687-a2b4-25de4e871753_MSRM.png",
        "scale_path": "imgs/review_images/ef439ec3-a802-4687-a2b4-25de4e871753_MSRM_scale.png",
        "band": 42,
        "vmin": -0.21336621046066284,
        "vmax": 0.26215672492980957,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/ef439ec3-a802-4687-a2b4-25de4e871753_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/ef439ec3-a802-4687-a2b4-25de4e871753_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.0849446058273315,
        "vmax": 1.3089572191238403,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.580689841197945, 71.74741162188543"
  },
  {
    "candidate_id": "ae382bb0-6e4d-46a0-a43b-0589b2d301a5",
    "median_probability": "74.7783780097961",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      765636.03013,
      3274770.33595,
      766776.03013,
      3275910.33595
    ],
    "review_square_side_m": 1140.0,
    "display_pixel_size_m": 1.425,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/ae382bb0-6e4d-46a0-a43b-0589b2d301a5_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/ae382bb0-6e4d-46a0-a43b-0589b2d301a5_SAVI (Wet).png",
        "scale_path": "imgs/review_images/ae382bb0-6e4d-46a0-a43b-0589b2d301a5_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/ae382bb0-6e4d-46a0-a43b-0589b2d301a5_MSRM.png",
        "scale_path": "imgs/review_images/ae382bb0-6e4d-46a0-a43b-0589b2d301a5_MSRM_scale.png",
        "band": 42,
        "vmin": -0.21272975206375122,
        "vmax": 0.2508005201816559,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/ae382bb0-6e4d-46a0-a43b-0589b2d301a5_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/ae382bb0-6e4d-46a0-a43b-0589b2d301a5_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.084101915359497,
        "vmax": 1.3050928115844727,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.579458961886132, 71.74804899420701"
  },
  {
    "candidate_id": "d9b65393-2998-4b9b-b18b-abc9af9af63f",
    "median_probability": "66.375333070755",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      1137320.5029039462,
      3429146.6778185996,
      1138410.5029039462,
      3430236.6778185996
    ],
    "review_square_side_m": 1090.0,
    "display_pixel_size_m": 1.3625,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/d9b65393-2998-4b9b-b18b-abc9af9af63f_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/d9b65393-2998-4b9b-b18b-abc9af9af63f_SAVI (Wet).png",
        "scale_path": "imgs/review_images/d9b65393-2998-4b9b-b18b-abc9af9af63f_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/d9b65393-2998-4b9b-b18b-abc9af9af63f_MSRM.png",
        "scale_path": "imgs/review_images/d9b65393-2998-4b9b-b18b-abc9af9af63f_MSRM_scale.png",
        "band": 42,
        "vmin": -0.16944777965545654,
        "vmax": 0.16625908017158508,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/d9b65393-2998-4b9b-b18b-abc9af9af63f_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/d9b65393-2998-4b9b-b18b-abc9af9af63f_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.1285483837127686,
        "vmax": 1.3066658973693848,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.82882804914545, 75.66253480979987"
  },
  {
    "candidate_id": "9959c68a-78c6-4325-b8ae-d8ad151c7571",
    "median_probability": "66.3710474967957",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      1049657.4675429426,
      3367922.0929802386,
      1050727.4675429426,
      3368992.0929802386
    ],
    "review_square_side_m": 1070.0,
    "display_pixel_size_m": 1.3375,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/9959c68a-78c6-4325-b8ae-d8ad151c7571_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/9959c68a-78c6-4325-b8ae-d8ad151c7571_SAVI (Wet).png",
        "scale_path": "imgs/review_images/9959c68a-78c6-4325-b8ae-d8ad151c7571_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/9959c68a-78c6-4325-b8ae-d8ad151c7571_MSRM.png",
        "scale_path": "imgs/review_images/9959c68a-78c6-4325-b8ae-d8ad151c7571_MSRM_scale.png",
        "band": 42,
        "vmin": -0.21128951013088226,
        "vmax": 0.22582079470157623,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/9959c68a-78c6-4325-b8ae-d8ad151c7571_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/9959c68a-78c6-4325-b8ae-d8ad151c7571_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.1018855571746826,
        "vmax": 1.3174254894256592,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.322898958443, 74.71850109718359"
  },
  {
    "candidate_id": "07eb1861-9689-4ca8-a2fb-b36e5677b322",
    "median_probability": "74.8442411422729",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      1043977.46754,
      3366622.09298,
      1045147.46754,
      3367792.09298
    ],
    "review_square_side_m": 1170.0,
    "display_pixel_size_m": 1.4625,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/07eb1861-9689-4ca8-a2fb-b36e5677b322_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/07eb1861-9689-4ca8-a2fb-b36e5677b322_SAVI (Wet).png",
        "scale_path": "imgs/review_images/07eb1861-9689-4ca8-a2fb-b36e5677b322_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/07eb1861-9689-4ca8-a2fb-b36e5677b322_MSRM.png",
        "scale_path": "imgs/review_images/07eb1861-9689-4ca8-a2fb-b36e5677b322_MSRM_scale.png",
        "band": 42,
        "vmin": -0.17727063596248627,
        "vmax": 0.1666540950536728,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/07eb1861-9689-4ca8-a2fb-b36e5677b322_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/07eb1861-9689-4ca8-a2fb-b36e5677b322_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.0620782375335693,
        "vmax": 1.211071491241455,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.31421695108405, 74.65957840766204"
  },
  {
    "candidate_id": "90048482-726b-4c12-ac84-d537c2b5eba2",
    "median_probability": "75.20936727523801",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      879118.54765,
      3366688.25158,
      880308.54765,
      3367878.25158
    ],
    "review_square_side_m": 1190.0,
    "display_pixel_size_m": 1.4875,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/90048482-726b-4c12-ac84-d537c2b5eba2_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/90048482-726b-4c12-ac84-d537c2b5eba2_SAVI (Wet).png",
        "scale_path": "imgs/review_images/90048482-726b-4c12-ac84-d537c2b5eba2_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/90048482-726b-4c12-ac84-d537c2b5eba2_MSRM.png",
        "scale_path": "imgs/review_images/90048482-726b-4c12-ac84-d537c2b5eba2_MSRM_scale.png",
        "band": 42,
        "vmin": -0.1539011001586914,
        "vmax": 0.15030604600906372,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/90048482-726b-4c12-ac84-d537c2b5eba2_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/90048482-726b-4c12-ac84-d537c2b5eba2_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.210710883140564,
        "vmax": 1.4117573499679565,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.377862363798965, 72.95050725674416"
  },
  {
    "candidate_id": "08396dc3-9bd1-44de-826e-74e47d3f8524",
    "median_probability": "92.8755223751068",
    "median_probability_category": "Very High",
    "image_size_px": 800,
    "review_square_bounds": [
      879618.64383,
      3343831.00337,
      880958.64383,
      3345171.00337
    ],
    "review_square_side_m": 1340.0,
    "display_pixel_size_m": 1.675,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/08396dc3-9bd1-44de-826e-74e47d3f8524_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/08396dc3-9bd1-44de-826e-74e47d3f8524_SAVI (Wet).png",
        "scale_path": "imgs/review_images/08396dc3-9bd1-44de-826e-74e47d3f8524_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/08396dc3-9bd1-44de-826e-74e47d3f8524_MSRM.png",
        "scale_path": "imgs/review_images/08396dc3-9bd1-44de-826e-74e47d3f8524_MSRM_scale.png",
        "band": 42,
        "vmin": -0.17626066505908966,
        "vmax": 0.18033765256404877,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/08396dc3-9bd1-44de-826e-74e47d3f8524_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/08396dc3-9bd1-44de-826e-74e47d3f8524_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.237365484237671,
        "vmax": 1.4972856044769287,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.172579893255033, 72.9482472885472"
  },
  {
    "candidate_id": "c1ab752f-9cb1-4f04-9687-1cb71e30603d",
    "median_probability": "93.1711971759796",
    "median_probability_category": "Very High",
    "image_size_px": 800,
    "review_square_bounds": [
      883823.64383,
      3338801.00337,
      885263.64383,
      3340241.00337
    ],
    "review_square_side_m": 1440.0,
    "display_pixel_size_m": 1.8,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/c1ab752f-9cb1-4f04-9687-1cb71e30603d_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/c1ab752f-9cb1-4f04-9687-1cb71e30603d_SAVI (Wet).png",
        "scale_path": "imgs/review_images/c1ab752f-9cb1-4f04-9687-1cb71e30603d_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/c1ab752f-9cb1-4f04-9687-1cb71e30603d_MSRM.png",
        "scale_path": "imgs/review_images/c1ab752f-9cb1-4f04-9687-1cb71e30603d_MSRM_scale.png",
        "band": 42,
        "vmin": -0.1633119285106659,
        "vmax": 0.1656118929386139,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/c1ab752f-9cb1-4f04-9687-1cb71e30603d_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/c1ab752f-9cb1-4f04-9687-1cb71e30603d_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.2056353092193604,
        "vmax": 1.4519429206848145,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.126411494446337, 72.99052651986226"
  },
  {
    "candidate_id": "1eccff6e-4606-4b7a-9aae-5bca446e7eea",
    "median_probability": "86.5707457065582",
    "median_probability_category": "Very High",
    "image_size_px": 800,
    "review_square_bounds": [
      1150184.75387,
      3269697.65818,
      1151434.75387,
      3270947.65818
    ],
    "review_square_side_m": 1250.0,
    "display_pixel_size_m": 1.5625,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/1eccff6e-4606-4b7a-9aae-5bca446e7eea_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/1eccff6e-4606-4b7a-9aae-5bca446e7eea_SAVI (Wet).png",
        "scale_path": "imgs/review_images/1eccff6e-4606-4b7a-9aae-5bca446e7eea_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/1eccff6e-4606-4b7a-9aae-5bca446e7eea_MSRM.png",
        "scale_path": "imgs/review_images/1eccff6e-4606-4b7a-9aae-5bca446e7eea_MSRM_scale.png",
        "band": 42,
        "vmin": -0.324441522359848,
        "vmax": 0.3190767467021942,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/1eccff6e-4606-4b7a-9aae-5bca446e7eea_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/1eccff6e-4606-4b7a-9aae-5bca446e7eea_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.1130939722061157,
        "vmax": 1.262689232826233,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.39359436998106, 75.69943093573625"
  },
  {
    "candidate_id": "ac439c99-99b2-45f8-9910-4e35c4ffc03e",
    "median_probability": "70.4861462116241",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      771797.72732,
      3378937.79077,
      772957.72732,
      3380097.79077
    ],
    "review_square_side_m": 1160.0,
    "display_pixel_size_m": 1.45,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/ac439c99-99b2-45f8-9910-4e35c4ffc03e_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/ac439c99-99b2-45f8-9910-4e35c4ffc03e_SAVI (Wet).png",
        "scale_path": "imgs/review_images/ac439c99-99b2-45f8-9910-4e35c4ffc03e_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/ac439c99-99b2-45f8-9910-4e35c4ffc03e_MSRM.png",
        "scale_path": "imgs/review_images/ac439c99-99b2-45f8-9910-4e35c4ffc03e_MSRM_scale.png",
        "band": 42,
        "vmin": -0.12462399154901505,
        "vmax": 0.12173540145158768,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/ac439c99-99b2-45f8-9910-4e35c4ffc03e_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/ac439c99-99b2-45f8-9910-4e35c4ffc03e_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.2191499471664429,
        "vmax": 1.4254709482192993,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.517132736328378, 71.83836630378894"
  },
  {
    "candidate_id": "7919817f-cf48-4b71-a19b-b3c03edd6239",
    "median_probability": "70.12081742286679",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      888495.71613,
      3338049.933,
      889635.71613,
      3339189.933
    ],
    "review_square_side_m": 1140.0,
    "display_pixel_size_m": 1.425,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/7919817f-cf48-4b71-a19b-b3c03edd6239_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/7919817f-cf48-4b71-a19b-b3c03edd6239_SAVI (Wet).png",
        "scale_path": "imgs/review_images/7919817f-cf48-4b71-a19b-b3c03edd6239_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/7919817f-cf48-4b71-a19b-b3c03edd6239_MSRM.png",
        "scale_path": "imgs/review_images/7919817f-cf48-4b71-a19b-b3c03edd6239_MSRM_scale.png",
        "band": 42,
        "vmin": -0.14712826907634735,
        "vmax": 0.1448134332895279,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/7919817f-cf48-4b71-a19b-b3c03edd6239_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/7919817f-cf48-4b71-a19b-b3c03edd6239_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.2523869276046753,
        "vmax": 1.4732459783554077,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=30.116866374878324, 73.03702599526817"
  },
  {
    "candidate_id": "e56a139f-05e7-43f6-8ffd-36a2f0fe807f",
    "median_probability": "85.0945770740509",
    "median_probability_category": "Very High",
    "image_size_px": 800,
    "review_square_bounds": [
      926869.71046,
      3539221.45285,
      928249.71046,
      3540601.45285
    ],
    "review_square_side_m": 1380.0,
    "display_pixel_size_m": 1.725,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/e56a139f-05e7-43f6-8ffd-36a2f0fe807f_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/e56a139f-05e7-43f6-8ffd-36a2f0fe807f_SAVI (Wet).png",
        "scale_path": "imgs/review_images/e56a139f-05e7-43f6-8ffd-36a2f0fe807f_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/e56a139f-05e7-43f6-8ffd-36a2f0fe807f_MSRM.png",
        "scale_path": "imgs/review_images/e56a139f-05e7-43f6-8ffd-36a2f0fe807f_MSRM_scale.png",
        "band": 42,
        "vmin": -0.1803416907787323,
        "vmax": 0.18545717000961304,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/e56a139f-05e7-43f6-8ffd-36a2f0fe807f_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/e56a139f-05e7-43f6-8ffd-36a2f0fe807f_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.105185627937317,
        "vmax": 1.3363622426986694,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=31.914725169626738, 73.52031662902185"
  },
  {
    "candidate_id": "9136dfe9-d013-4afa-836b-fbd9ddeb2d8a",
    "median_probability": "74.0904688835144",
    "median_probability_category": "High",
    "image_size_px": 800,
    "review_square_bounds": [
      835440.16718,
      3311451.0506,
      836650.16718,
      3312661.0506
    ],
    "review_square_side_m": 1210.0,
    "display_pixel_size_m": 1.5125,
    "images": [
      {
        "name": "rgb",
        "type": "rgb",
        "path": "imgs/review_images/9136dfe9-d013-4afa-836b-fbd9ddeb2d8a_rgb.png",
        "bands": [
          2,
          1,
          0
        ]
      },
      {
        "name": "SAVI (Wet)",
        "type": "colormap",
        "path": "imgs/review_images/9136dfe9-d013-4afa-836b-fbd9ddeb2d8a_SAVI (Wet).png",
        "scale_path": "imgs/review_images/9136dfe9-d013-4afa-836b-fbd9ddeb2d8a_SAVI (Wet)_scale.png",
        "band": 23,
        "vmin": -0.5,
        "vmax": 0.5,
        "cmap": "RdYlGn"
      },
      {
        "name": "MSRM",
        "type": "colormap",
        "path": "imgs/review_images/9136dfe9-d013-4afa-836b-fbd9ddeb2d8a_MSRM.png",
        "scale_path": "imgs/review_images/9136dfe9-d013-4afa-836b-fbd9ddeb2d8a_MSRM_scale.png",
        "band": 42,
        "vmin": -0.1787407100200653,
        "vmax": 0.1946433186531067,
        "cmap": "RdYlGn"
      },
      {
        "name": "Clay Mineral Ratio",
        "type": "colormap",
        "path": "imgs/review_images/9136dfe9-d013-4afa-836b-fbd9ddeb2d8a_Clay Mineral Ratio.png",
        "scale_path": "imgs/review_images/9136dfe9-d013-4afa-836b-fbd9ddeb2d8a_Clay Mineral Ratio_scale.png",
        "band": 25,
        "vmin": 1.1732338666915894,
        "vmax": 1.470781922340393,
        "cmap": "RdYlGn"
      }
    ],
    "google_maps_url": "https://maps.google.com/?q=29.89334094379152, 72.47942217479806"
  }
];
